// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfU-3tPR7j4G1OX77QgnwMxB14PyD2Jmw',
    appId: '1:232200820908:web:2fb796fbd0dd4d65f9e709',
    messagingSenderId: '232200820908',
    projectId: 'study-planner-jovac-grp1',
    authDomain: 'study-planner-jovac-grp1.firebaseapp.com',
    storageBucket: 'study-planner-jovac-grp1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlZT9QSKjHExIaoyLEYkjTaQP6gM_od-4',
    appId: '1:232200820908:android:80cc0b510f197eaef9e709',
    messagingSenderId: '232200820908',
    projectId: 'study-planner-jovac-grp1',
    storageBucket: 'study-planner-jovac-grp1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_lNGStMxUOtPJTRc0DyHfpoCeqlIEyXQ',
    appId: '1:232200820908:ios:e3fdbdfc29e0dd79f9e709',
    messagingSenderId: '232200820908',
    projectId: 'study-planner-jovac-grp1',
    storageBucket: 'study-planner-jovac-grp1.firebasestorage.app',
    iosBundleId: 'com.example.studyPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_lNGStMxUOtPJTRc0DyHfpoCeqlIEyXQ',
    appId: '1:232200820908:ios:e3fdbdfc29e0dd79f9e709',
    messagingSenderId: '232200820908',
    projectId: 'study-planner-jovac-grp1',
    storageBucket: 'study-planner-jovac-grp1.firebasestorage.app',
    iosBundleId: 'com.example.studyPlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfU-3tPR7j4G1OX77QgnwMxB14PyD2Jmw',
    appId: '1:232200820908:web:dd438b06e9136fcbf9e709',
    messagingSenderId: '232200820908',
    projectId: 'study-planner-jovac-grp1',
    authDomain: 'study-planner-jovac-grp1.firebaseapp.com',
    storageBucket: 'study-planner-jovac-grp1.firebasestorage.app',
  );
}
